config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only:[:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to:'static_pages#home'

  match '/signup', to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  default_scope order: 'microposts.created_at DESC'
  scope :from_users_followed_by, lambda { |user| followed_by(user) }

  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids.join(', ')
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end

  private

  def self.followed_by(user)
    followed_user_ids = %(SELECT followed_id FROM relationships WHERE follower_id = :user_id)
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", { user_id: user })
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                    class_name:  "Relationship",
                    dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  before_save :create_remember_token

  paginates_per 30
  validates :name, presence: true, length:{ maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user, only:[:create, :destroy]
  before_filter :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end

  private

  def correct_user
    @micropost = current_user.microposts.find_by_id(params[:id])
    redirect_to root_path if @micropost.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :signed_in_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' #Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.page(params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only:[:edit, :update]
  before_filter :admin_user, only: :destroy

  def index
    @users = User.page(params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def sign_out
    current_user = nil
    session.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  private

  def user_from_remember_token
    remember_token = session[:remember_token]
    User.find_by_remember_token(remember_token) unless remember_token.nil?
  end

  def clear_return_to
    session.delete(:return_to)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{href: 'http://railstutorial.org/'}Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li= link_to 'About', about_path
      %li= link_to 'Contact', contact_path
      %li
        %a{href: 'http://news.railstutorial.org/'}News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  %div.navbar-inner
    %div.container
      = link_to "sample app", root_path, id: "logo"
      %nav
      %ul.nav.pull-right
        %li= link_to "Home", root_path
        %li= link_to "Help", help_path
        - if signed_in?
          %li= link_to "Users", users_path
          %li#fat-menu.dropdown
            %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}Account
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li= link_to "Sign out", signout_path, method: "delete"
        - else
          %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
  %div.container
    - flash.each do |key, value|
      = content_tag(:div, value, class:"alert alert-#{key}")
    = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/microposts/_micropost.html.haml
%li
  %span.content
    = micropost.content
  %span.timestamp
    Posted
    = time_ago_in_words(micropost.created_at)
    ago.
  - if current_user?(micropost.user)
    = link_to "delete", micropost, method:  :delete,
                      confirm: "You sure?",
                      title:   micropost.content

app/views/relationships/create.js.haml
:plain
 $('#follow_form').html(
  "#{ escape_javascript(render('users/unfollow')) }"
 );
 $('#followers').html(
  "#{ @user.followers.count }"
 );

app/views/relationships/destroy.js.haml
:plain
 $('#follow_form').html(
  "#{ escape_javascript(render('users/follow')) }"
  );
 $('#followers').html(
   "#{ @user.followers.count }"
  );

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %div#error_explanation
    %div.alert.alert-error
      The form contains
      = pluralize(object.errors.count, "error")
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          *
          = msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
  = paginate @feed_items

app/views/shared/_feed_item.html.haml
%li(id="#{feed_item.id}")
  = link_to gravatar_for(feed_item.user), feed_item.user
  %span.user
    = link_to feed_item.user.name, feed_item.user
  %span.content
    = feed_item.content
  %span.timestamp
    Posted
    = time_ago_in_words(feed_item.created_at)
    ago.
    - if current_user?(feed_item.user)
      = link_to "delete", feed_item, method:  :delete,
                        confirm: "You sure?",
                        title:   feed_item.content

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  %div.field
    = f.text_area :content, placeholder: "Compose new micropost..."
    = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_stats.html.haml
- @user ||= current_user
%div.stats
  %a{href: "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.followed_users.count
    following
  %a{href: "#{followers_user_path(@user)}" }
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
%a{href: "#{user_path(current_user)}" }
  = gravatar_for current_user, size: 52
%h1= current_user.name
%span= link_to  "view my profile", current_user
%span= pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%h1 About Us
%p
  The
  %a{href: 'http://railstutorial.org/'}Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development
  with
  %a{href: 'http://rubyonrails.org/'}Ruby on Rails.
  This is he sample application for the tutorial.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  %a{href: 'http://railstutorial.org/contact'}contact page.

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  %a{href: 'http://railstutorial.org/help'}Rails Tutorial help page
  To get help on this sample app, see the
  %a{href: 'http://railstutorial.org/book'}Rails Tutorial book

app/views/static_pages/home.html.haml
- if signed_in?
  %div.row
    %aside.span4
      %section
        = render 'shared/user_info'
      %section
        = render 'shared/stats'
      %section
        = render 'shared/micropost_form'
    %div.span8
      %h3 Micropost Feed
      = render 'shared/feed'
- else
  %div.center.hero-unit
    %h1 Welcome to the Sample App

    %h2
      Tis is the home page for the
      %a{href: 'http://railstutorial.org/'}Ruby on Rails Tutorial
      sample application.

    = link_to "Sign up now!", signup_path, class:"btn btn-large btn-primary"

  = link_to image_tag("rails.png", alt:"Rails"),'http://rubyonrails.org/'

app/views/users/_fields.html.haml
= f.label :name
= f.text_field :name

= f.label :email
= f.text_field :email

= f.label :password
= f.password_field :password

= f.label :password_confirmation, "Confirmation"
= f.password_field :password_confirmation

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f|
  %div
    = f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-large btn-primary"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  %div#follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.find_by_followed_id(@user), html:{ method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-large"

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 52
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |
    = link_to "delete", user, method: :delete, confirm: "You sure?"

app/views/users/edit.html.haml
- provide(:title, 'Edit user')
%h1 Update your profile

= form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object
  = render 'fields', f: f
  = f.submit "Save changes", class: "btn btn-large btn-primary"
= gravatar_for @user
%a{href: 'http://gravatar.com/emails', target: "_blank" }Change

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users

= paginate @users

%ul.users
  = render @users

= paginate @users

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up

= form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object
  = render 'fields', f: f
  = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
%div.row
  %aside.span4
    %section
      %h1
        = gravatar_for @user
        = @user.name
    %secrion
      = render 'shared/stats'
  %div.span8
    =render 'follow_form' if signed_in?
    - if @user.microposts.any?
      %h3
        Microposts
        (
        = @user.microposts.count
        )
      %ol.microposts
        = render @microposts
      = paginate @microposts

app/views/users/show_follow.html.haml
- provide(:title, @title)
%div.row
  %aside.span4
    %secrion
      = gravatar_for @user
      %h1
        = @user.name
      %span
        = link_to "view my profile", @user
      %span
        %b Microposts:
        = @user.microposts.count
      = render 'shared/stats'
      - unless @users.empty?
        %div.user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  %div.span8
    %h3
      = @title
      - if @users.any?
        %ul.users
          = render @users
        = paginate @users